name: API Tests on Heroku

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python version
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.4'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate  # Activation de l'environnement virtuel
          pip install -r requirements.txt
          pip install pytest

      - name: Run API tests
        run: |
          source venv/bin/activate  # Assure que venv est activé avant pytest
          pytest Tests_unitaires/test_api.py
